add namespace autoloader
jeedom/core pull request #2910
Opened 2024-09-22 11:47 UTC by pifou25

## Description

Bonjour,
Je propose d'ajouter la gestion de namespaces dans l'autoloader de Jeedom. Le namespace permet d'éviter des conflits de classes qui auraient le même nom, en particulier avec tous les plugins. Cela permettra à chaque plugin de faire ce qu'il veut dans son propre namespace. Et autre avantage, toutes les classes des plugins seront automatiquement chargées.
_En plus, la fonction autoloader pourra être simplifié si jamais un jour on arrive à migrer toutes les classes dans leur namespace respectif._
En attendant, mon évolution est retro-compatible, je laisse tous les chargements spécifiques actuels. Et le namespace conserve les répertoires actuels, par exemple :

Les classes du core:
use jeedom\core\class\NewClass --> __DIR__/core/class/NewClass.class.php
les classes des plugins:
use jeedom\plugin\atlas\core\class\atlas --> __DIR__/plugin/atlas/core/class/atlas.class.php
on peut continuer ainsi avec les classes spécifiques com_* ou repo_*:
use jeedom\core\class\repo\github --> __DIR__/core/class/repo/github.class.php

Bref, ... déplacer les classes existantes est plutôt dangereux je suppose, mais par contre on peut simplement créer de nouvelles classes avec namespace et adopter cette convention au fil de l'eau...
Il y a encore plein de code php en dehors de toute classe, qui gagnerait à être déplacé dans de nouvelles classes.

### Suggested changelog entry

### Related issues/external references

Fixes #

## Types of changes

- [ ] Bug fix _(non-breaking change which fixes)_
- [ ] New feature _(non-breaking change which adds functionality)_
- [ ] Breaking change _(fix or feature that would cause existing functionality to change)_
    - [ ] This change is only breaking for integrators, not for external standards or end-users.
- [ ] Documentation improvement

## PR checklist

- [ ] I have checked there is no other PR open for the same change.
- [ ] I have read the [[La ligne directrice pour contribuer à ce projet / Contribution guidelines for this project](.github/CONTRIBUTING.md)).
- [ ] I grant the project the right to include and distribute the code under the GNU.
- [ ] I have added tests to cover my changes.
- [ ] I have verified that the code complies with the projects coding standards.
- [ ] [Required for new sniffs] I have added MD documentation for the sniff.

2025-05-24 07:30 UTC, kwizer15 commented on core/php/core.inc.php
> +	} else if (file_exists($path)) {
Est-ce qu'on ne pourrait pas utiliser directement l'autoloader de composer pour les classes du core ? Ça permettrait d'enlever de la logique ici et ca serait probablement plus optimisé.

2025-05-24 16:34 UTC, pifou25 commented on core/php/core.inc.php
> +	} else if (file_exists($path)) {
En l'état ce n'est pas possible à cause de cette extension baroque .class.php ... Mais, admettons qu'on renomme toutes les classes en *.php ça pourrait marcher, on ajoute la définition dans `composer.json`
```
  "autoload": {
      "psr-4": {
          "Jeedom\\": ""
      }
    }
```
Et ainsi la classe avec le namespace `Jeedom\core\class\eqLogic.php` sera automatiquement chargée.

2025-05-24 19:10 UTC, kwizer15 commented on core/php/core.inc.php
> +	} else if (file_exists($path)) {
Je pensais plus a `classmap` ou `files` que psr-4. Y a plusieurs façon d'autoloader dans composer.
https://getcomposer.org/doc/04-schema.md#autoload

Dans tout les cas ce n'est pas gérable pour le moment pour les plugins, mais pour le core c'est surement intéressant.

2025-07-06 18:42 UTC, kwizer15 commented on composer.json
> +      "plugins/*/core/class/"
J'ai juste un doute : si on installe un plugin, tout est bien pris en compte ? Il faut peut-être forcer un `composer dumpautoload` apres les installations/desinstallations de plugins, et potentiellement les maj de jeedom.

2025-07-15 17:06 UTC, pifou25 commented on composer.json
> +      "plugins/*/core/class/"
oui en effet, il faudrait refaire un `composer dump-autoload` pour regénérer l'autoloader après chaque installation / suppression de plugin, et je ne sais pas à quel endroit dans le code on peut insérer ça, il n'y a pas de hook simple donc je suppose dans la classe du core update...
Pour les maj de jeedom, peut être pas, en principe une maj est susceptible d'ajouter / modifier les dépendances Composer et donc ça doit déjà faire un `composer install` dans tous les cas.

2025-07-15 17:12 UTC, kwizer15 commented
Ça doit pouvoir s'appeler directement depuis le code php de composer. Je
veux dire, sans passer par la commande. Le mieux c'est surement de
l'intégrer directement après le d/l du plugin.

Je suis assez d'accord pour l'update de jeedom, mais c'est à vérifier tout
de même.

Le mar. 15 juil. 2025, 19:06, Pifou25 ***@***.***> a écrit :

> ***@***.**** commented on this pull request.
> ------------------------------
>
> In composer.json
> <https://github.com/jeedom/core/pull/2910#discussion_r2208066715>:
>
> > +  },
> +  "autoload": {
> +    "psr-4": {
> +      "Jeedom\\plugins\\": "plugins/"
> +    },
> +    "files": [
> +      "core/config/common.config.php",
> +      "core/php/utils.inc.php",
> +      "core/config/jeedom.config.php",
> +      "core/config/compatibility.config.php"
> +    ],
> +    "classmap": [
> +      "core/class/",
> +      "core/com/",
> +      "core/repo/",
> +      "plugins/*/core/class/"
>
> oui en effet, il faudrait refaire un composer dump-autoload pour
> regénérer l'autoloader après chaque installation / suppression de plugin,
> et je ne sais pas à quel endroit dans le code on peut insérer ça, il n'y a
> pas de hook simple donc je suppose dans la classe du core update...
> Pour les maj de jeedom, peut être pas, en principe une maj est susceptible
> d'ajouter / modifier les dépendances Composer et donc ça doit déjà faire un composer
> install dans tous les cas.
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/jeedom/core/pull/2910#discussion_r2208066715>, or
> unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AAEKOTTIS4LQ2ZEQMDGQ4PD3IUYI5AVCNFSM6AAAAABOUPRCRWVHI2DSMVQWIX3LMV43YUDVNRWFEZLROVSXG5CSMV3GSZLXHMZTAMRRGMZTKMBRGQ>
> .
> You are receiving this because you commented.Message ID:
> ***@***.***>
>

2025-07-15 17:47 UTC, pifou25 commented on composer.json
> +      "plugins/*/core/class/"
C'est bon je crois que j'ai trouvé, dans core/class/update.class.php::doUpdate ça marche au moins pour l'installation depuis le market, je n'ai pas testé les autres types d'install de plugin mais ça devrait faire pareil:

> [2025-07-15 19:36:47][DEBUG] Composer autoloader dump result:
> Generating optimized autoload files
> Generated optimized autoload files containing 869 classes
>

2025-07-15 20:29 UTC, pifou25 commented
Bon j'ai un problème avec l'include de core/config/jeedom.config.php
la config auto utilise la fonction __ de traduction qui va chercher la connexion à la db, évidemment il n'y en a pas et ça fait planter le job phpstan...
Je dois supprimer l'auto include de ce fichier de config ? Autre solution, on n'utilise plus la db pour faire les traductions, il faut retoucher un poil la classe translate mais c'est possible ?

2025-07-15 20:48 UTC, kwizer15 commented
> Bon j'ai un problème avec l'include de core/config/jeedom.config.php la config auto utilise la fonction __ de traduction qui va chercher la connexion à la db, évidemment il n'y en a pas et ça fait planter le job phpstan... Je dois supprimer l'auto include de ce fichier de config ? Autre solution, on n'utilise plus la db pour faire les traductions, il faut retoucher un poil la classe translate mais c'est possible ?

Pour moi, à terme, le fichier jeedom.config.php n’est pas un fichier à autoloader. Mais ça ne règle pas le problème immédiat. Le problème n’est pas réellement les traductions, mais l’accès à la base.
Ce que tu peux essayer de faire, c’est de modifier la fonction de trad pour gérer l’exception de non-connection à la base et faire un fallback en renvoyant simplement la clé de traduction.

2025-07-15 21:04 UTC, kwizer15 commented
En gros faire ca dans la classe translate

```diff
public static function getConfig($_key, $_default = '') {
		if (self::$config === null) {
+            try {
                self::$config = config::byKeys(array('language'));
+            } catch (Exception $e) {
+                self::$config = array();
+            }
		}
		if (isset(self::$config[$_key])) {
			return self::$config[$_key];
		}
		return $_default;
	}
```

2025-07-16 17:09 UTC, kwizer15 requested changes

2025-07-16 17:09 UTC, kwizer15 commented on core/class/translate.class.php
> +				log::add('debug_translate', 'warning', $e.getMessage());
$e->getMessage()

2025-07-16 17:21 UTC, pifou25 commented on core/class/translate.class.php
> +				log::add('debug_translate', 'warning', $e.getMessage());
ha, oui, désolé, l'habitude du java... merci 👍

2025-07-16 17:28 UTC, kwizer15 commented
Ah ça veut pas ! 😅

2025-07-16 17:41 UTC, pifou25 commented
> Ah ça veut pas ! 😅

ben non, vraiment pas... Et la, je ne vois pas pourquoi, on dirait que quelqu'un ou quelque chose déclenche malgré tout une tentative de connexion à la db. Peut être un appel à la classe log quelque part ?

2025-07-16 18:24 UTC, kwizer15 commented
Je pense qu’il y a un soucis de conception à la base. J’ai mon idée de comment "corriger" mais c’est pas léger. Je te propose de faire sans les fichiers qui posent problème dans un premier temps (jeedom.config.php et d’autres si c’est le cas) et de garder le fonctionnement actuel pour ces fichiers. On essaiera de les gérer dans un second temps sur une autre PR.

2025-07-16 21:09 UTC, pifou25 commented
J'ai donc enlevé jeedom.config.php de l'autoloader Composer et remis dans core.inc.php 
et phpstan est heureux :) et je ne comprends pas pourquoi il ne passait pas :( 
Il faudrait mettre cette constante dans une classe avec un init au runtime, mais ça change l'appel et il faudrait voir partout où cette constante est appelée...

2025-07-16 21:15 UTC, kwizer15 commented
C'est à peu près mon idée. Pour moi faudrait transformer ce tableau en un objet qui implémente ArrayAccess. Ca permettrait de garder l'utilisation actuelle, mais aussi de l'initialiser seulement au premier accès.
Je sais pas encore si ca vaut le coup, par experience, c'est pas complètement safe à faire.

2025-09-14 13:11 UTC, kwizer15 requested changes
**Proposition de modification du fichier jeedom.config.php**

Référence : https://github.com/kwizer15/core/blob/d76183abb920a394ce191bb5cc82f40d025fa48a/core/config/jeedom.config.php

**Approche adoptée :**
Cette solution s'appuie sur votre concept de `__toString` tout en résolvant le problème des concaténations directes présentes dans la configuration actuelle.

**Implémentation :**
- Création d'un objet Translation contenant :
  - La clé de traduction
  - Un préfixe (optionnel)
  - Un suffixe (optionnel) 
  - Les deux paramètres de traduction existants (qui conservent leurs valeurs par défaut dans notre contexte)

- Introduction de la fonction `t()` : similaire à `__()` mais génère directement un objet Translation avec support de `__toString`
- Possibilité d'ajouter un préfixe et un suffixe non traduits à la fonction `t()`

**Avantage principal :**
L'évaluation de `__toString` est différée jusqu'à l'utilisation effective, évitant ainsi son déclenchement prématuré lors du chargement de la configuration.

**Note :** L'extraction de la classe et de la fonction interne reste optionnelle selon les besoins.

2025-09-14 13:11 UTC, kwizer15 commented on core/class/translate.class.php
> -			self::$config = config::byKeys(array('language'));
tu peux revenir à cette version

2025-09-14 13:11 UTC, kwizer15 commented on core/class/log.class.php
> -			self::$config = array_merge(config::getLogLevelPlugin(), config::byKeys(array('log::engine', 'log::formatter', 'log::level', 'addMessageForErrorLog', 'maxLineLog')));
tu peux revenir à cette version

2025-09-14 13:11 UTC, kwizer15 commented on core/php/core.inc.php
>  include_file('core', 'compatibility', 'config');
à supprimer (c’est dans le composer)

2025-09-14 13:11 UTC, kwizer15 commented on core/php/core.inc.php
> +spl_autoload_register('jeedomAutoload', true, false);
```
spl_autoload_register('jeedomAutoload')
```

2025-09-14 13:16 UTC, kwizer15 commented on core/php/core.inc.php
> +	if (strpos($_classname, '\\') === false && strpos($_classname, '/') === false) {
(optionel) tu peux faire
```suggestion
	if (strpos($_classname, '\\') !== false && strpos($_classname, '/') !== false) {
	    return;
	}
```
et mettre le reste du code ensuite, ça réduira l’indentation, c’est toujours plus agréable à lire.

2025-09-14 13:20 UTC, kwizer15 commented on core/php/core.inc.php
> +/**
(optionel, pour au-dessus)
changer les 
```
} catch (Exception $e) {
} catch (Error $e) {
}
```

par

```
} catch (Throwable $e) {
    log::add('jeedom', 'error', 'Log (level|timezone) configuration failed: ' . $e->getMessage());)
}
```

2025-09-14 14:17 UTC, kwizer15 commented on composer.json
> +      "Jeedom\\plugins\\": "plugins/"
```suggestion
      "Jeedom\\Plugins\\": "plugins/"
```

pour respecter la PSR-4

2025-09-14 14:17 UTC, kwizer15 commented on composer.json
> +      "Jeedom\\plugins\\": "plugins/"
(optionel) Rajouter un 
```
  "Jeedom\\Core\\": "src/"
```

pour permettre d’initialiser de nouvelles classes PSR-4 (futur PR?)

2025-09-14 15:27 UTC, kwizer15 commented on composer.json
> +      "Jeedom\\plugins\\": "plugins/"
Je reviens sur cette ligne PSR-4. En mappant le dossier plugins vers le namespace Jeedom\plugins, on force tous les plugins existants à adopter ce namespace, ce qui pose problème :

- Soit on demande à tous les développeurs de plugins de migrer leurs classes vers ce nouveau namespace (breaking change majeur)
- Soit on implémente un système d'alias de classes dans le core pour faire le pont (ajout de complexité technique)

Pour une PR dont l'objectif est d'ajouter l'autoload Composer, ça me semble sortir du périmètre et apporter une complexité disproportionnée. Je pense qu'il vaut mieux retirer cette ligne et traiter la standardisation des namespaces des plugins dans un autre ticket dédié.

2025-09-14 15:54 UTC, pifou25 commented on composer.json
> +      "Jeedom\\plugins\\": "plugins/"
Non je ne force rien du tout cas j'ai laissé l'autoloader spécifique existant pour les plugins, celui dans core.inc.php.

ça permet juste aux futurs plugins d'utiliser l'autoloader normalisé PSR-4 de Composer au lieu de celui spécifique à Jeedom. Mais ça ne permet pas de remplacer la classe de base du plugin qui doit rester avec la convention Jeedom et sans namespace `[pluginid].class.php` ni même la classe `*cmd.class.php`

2025-09-14 16:05 UTC, pifou25 commented on core/class/log.class.php
> -			self::$config = array_merge(config::getLogLevelPlugin(), config::byKeys(array('log::engine', 'log::formatter', 'log::level', 'addMessageForErrorLog', 'maxLineLog')));
Je préfère laisser le try / catch ici, pour une classe de log elle doit être robuste. D'autant que j'ajoute des log dans la fonction d'autoloader.

2025-09-14 16:11 UTC, pifou25 commented
Merci pour tes retours je les ai pris en compte :) 
Je vais laisser le fichier `jeedom.config.php` tel quel, ça mérite de faire une autre PR pour ce sujet, avec la reprise de la fonction __() de partout.

2025-09-14 16:23 UTC, kwizer15 commented
Ok  pense juste a remettre le incluse dans le core dans ce cas.

Le dim. 14 sept. 2025, 18:12, Pifou25 ***@***.***> a écrit :

> *pifou25* left a comment (jeedom/core#2910)
> <https://github.com/jeedom/core/pull/2910#issuecomment-3289659213>
>
> Merci pour tes retours je les ai pris en compte :)
> Je vais laisser le fichier jeedom.config.php tel quel, ça mérite de faire
> une autre PR pour ce sujet, avec la reprise de la fonction __() de partout.
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/jeedom/core/pull/2910#issuecomment-3289659213>, or
> unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AAEKOTULM3L6QMF5OSXIDR33SWHVBAVCNFSM6AAAAABOUPRCRWVHI2DSMVQWIX3LMV43OSLTON2WKQ3PNVWWK3TUHMZTEOBZGY2TSMRRGM>
> .
> You are receiving this because you commented.Message ID:
> ***@***.***>
>

2025-09-14 18:11 UTC, kwizer15 approved these changes

2025-09-15 07:00 UTC, pifou25 commented on composer.json
> +      "Jeedom\\plugins\\": "plugins/"
je n'ai pas répondu avant, pourquoi pas ajouter un namespace pour les classes du core mais dans ce cas, pourquoi dans src ? je l'aurais laissé dans /core/class ou un autre rep du /core pour conserver la structure actuelle.

2025-09-15 08:19 UTC, kwizer15 commented on composer.json
> +      "Jeedom\\plugins\\": "plugins/"
Je comprends ta question sur le choix de `src/`. L'idée derrière cette approche, c'est de préparer une migration progressive vers du PSR-4 moderne.

Pourquoi `src/` plutôt que garder dans `/core/class` ? Plusieurs raisons :

**1. Standards de l'écosystème**
PSR-4 recommande `src/` comme racine pour les classes namespacées. Ça nous alignerait sur ce que fait tout l'écosystème PHP aujourd'hui, ce qui faciliterait l'intégration avec les outils modernes (IDE, analyseurs de code, etc.).

**2. Clarté de la migration**
En gardant deux arbos distinctes :
- `/core/class/` → l'ancien système (fichiers `*.class.php`)
- `src/` → le nouveau (classes PSR-4 propres)

On évite le mélange des genres et c'est plus clair pour tout le monde ce qui est "legacy" vs "moderne".

**3. Stratégie de transition**
L'objectif c'est que les anciennes classes deviennent des « wrappers » qui appellent les nouvelles implémentations. Comme ça, zero breaking change pour les plugins existants, mais on peut développer du code plus propre en interne.

Au final, c'est plus une question de préparation pour l'avenir que de besoin immédiat. Mais si on veut un jour pouvoir faire évoluer Jeedom vers des pratiques plus modernes, autant poser les bonnes bases dès maintenant.

Ça permettrait, par exemple, de mettre immédiatement la classe `Translation` (ou `Trad`) de la configuration `jeedom.config.php` dans un namespace dédié et d’éviter les confusions avec la classe `translate` déjà existante.

Qu'est-ce que tu en penses ?

2025-09-21 15:01 UTC, pifou25 commented on composer.json
> +      "Jeedom\\plugins\\": "plugins/"
ok pour /src moi ça me va très bien

2026-04-18 08:58 UTC, Mips2648 commented
Cette PR target alpha qui n'est plus valide.
De plus, avant de se lancer dans une PR de ce type, je pense qu'il est préférable de discuter de la pertinence via une issue pour être certain qu'un membre de l'équipe se charge de review et d'intégrer cette PR dans le core sinon c'est beaucoup de travail pour la maintenir en vie jusqu'à ce que ce soit le bon moment pour l'intégrer
=> Je ferme

2026-04-18 08:58 UTC, closed without merging

2026-04-19 07:52 UTC, kwizer15 commented
Issue #3108