Add healthcheck
jeedom/core pull request #2998
Opened 2024-12-17 20:25 UTC by pifou25

## Description

Le healtchckeck dans le Dockerfile permet nativement à Docker de savoir la santé du container, c'est pratique pour le monitoring, on peut directement voir dans un simple `docker run ...` s'il a fini de démarrer ou pas... Et ça n'empêche pas de surcharger ce healtchcheck dans docker-compose ou ailleurs, on peut le voir comme un healthcheck par défaut.

Et on l'utilise dans le workflow github au lieu du `sleep45` pour attendre la fin du démarrage.

### Suggested changelog entry

* Healthcheck for Dockerfile

### Related issues/external references

Fixes #

## Types of changes

- [ ] Bug fix _(non-breaking change which fixes)_
- [ ] New feature _(non-breaking change which adds functionality)_
- [ ] Breaking change _(fix or feature that would cause existing functionality to change)_
    - [ ] This change is only breaking for integrators, not for external standards or end-users.
- [ ] Documentation improvement

## PR checklist

- [ ] I have checked there is no other PR open for the same change.
- [ ] I have read the [[La ligne directrice pour contribuer à ce projet / Contribution guidelines for this project](.github/CONTRIBUTING.md)).
- [ ] I grant the project the right to include and distribute the code under the GNU.
- [ ] I have added tests to cover my changes.
- [ ] I have verified that the code complies with the projects coding standards.
- [ ] [Required for new sniffs] I have added MD documentation for the sniff.

2024-12-18 12:31 UTC, zoic21 approved these changes

2026-04-16 16:36 UTC, Mips2648 requested changes
Bonjour,

Il faudrait corriger cette PR ou la re-soumettre pour n'avoir que le changement sur le dockerfile stp

2026-04-19 13:11 UTC, pifou25 commented
> Il faudrait corriger cette PR ou la re-soumettre pour n'avoir que le changement sur le dockerfile stp

Voila*à c'est fait :) ajout du healthcheck dans le Dockerfile + utilisation dans le workflow docker-test.yml

2026-04-19 13:17 UTC, Mips2648 approved these changes

2026-04-19 13:18 UTC, merged